name: flutter_presensi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  freezed_annotation: ^2.4.4
  provider: ^6.1.2
  get_it: ^7.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  flutter_osm_plugin: ^1.3.2
  geolocator: ^13.0.1
  device_info_plus: ^10.1.2
  flutter_face_api: ^6.2.3
  flutter_face_core_basic: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.2
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
